---
  {{ define "sds_drbd_data_nodes_node_selector" }}
nodeSelector:
  {{- . | toYaml | nindent 2 }}
  {{- end }}
  ---
apiVersion: v1
kind: Secret
metadata:
  name: d8-sds-drbd-operator-config
  namespace: d8-{{ .Chart.Name }}
type: Opaque
stringData:
  config: |
{{- if dig "dataNodes" "nodeSelector" false .Values.linstor }}
  {{ template "sds_drbd_data_nodes_node_selector" .Values.linstor.dataNodes.nodeSelector | nindent 4 }}
{{- else}}
    nodeSelector:
      kubernetes.io/os: linux
{{- end }}
