---
apiVersion: v1
kind: Secret
metadata:
  name: d8-sds-drbd-operator-config
  namespace: d8-{{ .Chart.Name }}
type: Opaque
stringData:
  config: |-
    nodeSelector: {{ .Values.linstor.dataNodes.nodeSelector | toYaml | nindent 6 }}
