---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    heritage: deckhouse
    module: deckhouse
  name: projecttypes.deckhouse.io
spec:
  group: deckhouse.io
  names:
    kind: ProjectType
    listKind: ProjectTypeList
    plural: projecttypes
    singular: projecttype
  scope: Cluster
  versions:
    - additionalPrinterColumns:
        - jsonPath: .status.ready
          name: Ready
          type: boolean
      name: v1alpha1
      schema:
        openAPIV3Schema:
          description: |
            Describes the template of project resources and the OpenAPI schema for the template parameters.

            This resource is referenced by the [Project](cr.html#project) CR.
          properties:
            spec:
              properties:
                namespaceMetadata:
                  description:
                    Labels and annotations that apply to created namespaces when setting up the project.
                  properties:
                    annotations:
                      additionalProperties:
                        type: string
                      type: object
                    labels:
                      additionalProperties:
                        type: string
                      type: object
                  type: object
                openAPI:
                  additionalProperties:
                    x-kubernetes-preserve-unknown-fields: true
                  description:
                    OpenAPI specification for template values (the [resourcesTemplate](#projecttype-v1alpha1-spec-resourcestemplate) parameter).
                  type: object
                resourcesTemplate:
                  description: |
                    Helm template of resources that will be created when setting up a new project.

                    Templates are fully compatible with all `helm` functions. Read more about [creating an isolated Environment](usage.html#creating-an-isolated-project)...

                    The following values are also available in templates:
                    - `{{ .projectName }}` — the name of the `Project` for which the template is being rendered.
                    - `{{ .projectTypeName }}` — the name of the `ProjectType`.
                    - `{{ .params }}` — a dictionary of custom values, described in the [.spec.openAPI](cr.html#projecttype-v1alpha1-spec-openapi) parameter and defined in the [.spec.template](cr.html#project-v1alpha1-spec-template) parameter.

                    > **Note!** Objects with missing `.metadata.namespace` will be assigned with one
                    > set to the name of the created project (CR `Project`).
                  type: string
                subjects:
                  description:
                    List of ServiceAccounts, Groups and Users to provide access to the created project.
                  items:
                    oneOf:
                      - properties:
                          kind:
                            enum:
                              - ServiceAccount
                          name: {}
                          namespace: {}
                          role: {}
                        required:
                          - kind
                          - name
                          - namespace
                          - role
                      - properties:
                          kind:
                            enum:
                              - User
                              - Group
                          name: {}
                          role: {}
                        required:
                          - kind
                          - name
                          - role
                    properties:
                      kind:
                        description: |
                          Kind of the subject resource: `ServiceAccount`, `Group` or `User`.
                        enum:
                          - ServiceAccount
                          - User
                          - Group
                        type: string
                      name:
                        description: |
                          The name of the subject.
                        minLength: 1
                        type: string
                      namespace:
                        description: |
                          The namespace of the ServiceAccount resource.

                          Required only when using `ServiceAccount` from another namespace.
                        pattern: "[a-z0-9]([-a-z0-9]*[a-z0-9])?"
                        type: string
                      role:
                        description: Role name from [user-authz module](../140-user-authz/cr.html#clusterauthorizationrule-v1-spec-accesslevel)
                        enum:
                          - User
                          - PrivilegedUser
                          - Editor
                          - Admin
                        type: string
                    type: object
                  type: array
              type: object
            status:
              properties:
                message:
                  description: Status message.
                  type: string
                ready:
                  description: Summary of the status (ready or not ready).
                  type: boolean
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
